name: "Build"
on: [push]
steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      java-version: '17'
      distribution: 'temurin'
  - name: Builds
    run: mvn
  - uses: actions/upload-artifact@v4
    with:
      name: GeyserModelEngine
      path: "target/*.jar"
